# Generated by Django 5.0.6 on 2024-06-23 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("airlines_code", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="A unique identifier for each ticket",
                    ),
                ),
                ("origin", models.CharField(max_length=60)),
                ("flight_from_date", models.DateTimeField()),
                ("destination", models.CharField(max_length=60)),
                ("flight_to_date", models.DateTimeField()),
                ("total_passengers", models.PositiveBigIntegerField()),
                ("price", models.FloatField()),
                (
                    "stops",
                    models.CharField(
                        choices=[
                            ("Direct", "direct"),
                            ("1 stop", "1 stop"),
                            ("2 stop", "2 stop"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "cabin_class",
                    models.CharField(
                        choices=[
                            ("economy", "economy"),
                            ("premium_economy", "premium_economy"),
                            ("business", "business"),
                            ("first_class", "first_class"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airlines",
                        to="ticket_app.airline",
                    ),
                ),
            ],
        ),
    ]
