# Generated by Django 5.0.6 on 2024-06-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="destination",
            new_name="arrival",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="flight_from_date",
            new_name="arriving_date",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="flight_to_date",
            new_name="departing_date",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="origin",
            new_name="departure",
        ),
        migrations.AddField(
            model_name="ticket",
            name="airplane",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="allowed_weight",
            field=models.FloatField(default=20, verbose_name="Must be in Kilogram"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="booked_up",
            field=models.BooleanField(
                default=False,
                verbose_name="Means that all the tickets have been booked",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[("one_way", "One Way"), ("round_trip", "Round Trip")],
                default=("one_way", "One Way"),
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cabin_class",
            field=models.CharField(
                choices=[
                    ("economy", "Economy"),
                    ("premium_economy", "Premium Economy"),
                    ("business", "Business"),
                    ("first_class", "First Class"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="stops",
            field=models.CharField(
                choices=[
                    ("direct", "Direct"),
                    ("1 stop", "1 stop"),
                    ("2 stop", "2 Stops"),
                ],
                max_length=10,
            ),
        ),
    ]
