# Generated by Django 5.0.6 on 2024-06-27 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_app", "0002_rename_destination_ticket_arrival_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="return_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Just use this field if you have chosen 'Round Trip'",
            ),
        ),
        migrations.CreateModel(
            name="TicketBooked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets_booked",
                        to="ticket_app.ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passengers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "passengers_type",
                    models.CharField(
                        choices=[
                            ("adults", "Adult"),
                            ("child", "Child"),
                            ("infant", "Infant"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_passengers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket_booked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="ticket_app.ticketbooked",
                    ),
                ),
            ],
        ),
    ]
