# Generated by Django 5.0.6 on 2024-06-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_app", "0003_alter_ticket_return_date_ticketbooked_passengers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passengers",
            name="user",
        ),
    ]
