# Generated by Django 5.0.6 on 2024-06-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_app", "0004_remove_passengers_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passengers",
            old_name="passengers_type",
            new_name="type",
        ),
    ]
