# Generated by Django 5.0.6 on 2024-06-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_app", "0006_alter_passengers_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="passengers",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passengers",
            name="first_name",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="passengers",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "Female"), ("male", "Male")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="passengers",
            name="last_name",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
