# Generated by Django 5.0.6 on 2024-06-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_app", "0007_passengers_date_of_birth_passengers_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passengers",
            name="type",
            field=models.CharField(
                choices=[
                    ("adults", "Adult"),
                    ("children", "Child"),
                    ("infants", "Infant"),
                ],
                max_length=10,
            ),
        ),
    ]
